#!/bin/sh

YANDEXDNS=/tmp/mnt/FLASH/yandexdns

if which python3 >/dev/null; then
    python3 $YANDEXDNS/yandexdns.py $YANDEXDNS/settings.conf --ip $1

    if [ $? -eq 0 ]; then
        logger -t YANDEXDNS 'Updating DDNS finished successfully'
        /sbin/ddns_custom_updated 1
    else
        logger -t YANDEXDNS 'Updating DDNS failed'
        /sbin/ddns_custom_updated 0
    fi
else
    /sbin/ddns_custom_updated 0
fi

